name: Tests unitaire de l'app

on: push

jobs:
  Tests-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12, 14, 16]
    steps:
      - name: recuperation du Repository 
        uses: actions/checkout@v3
      - name: installation de nodeJS
        run: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Info sur la version testé
        run: echo ${{ matrix.node-version }}
      - name: Installation des dépendances
        run: npm installation
      - name: Execution des tests unitaires
        run: npm test
      - name: Execution du code coverage
        run: npm run cover
        uses: actions/upload-artefact@v3
        with:
          name: reports
          path: ./reports/**